### PR TITLE
Enables verifying of certs

### PR DESCRIPTION
**Pull request by moebrowne**
Peer verification should ALWAYS be enabled. Disabling it prevents authenticity checks and facilitates man in the middle attacks.

- https://secure.php.net/manual/en/function.curl-setopt.php#110457
- https://stackoverflow.com/questions/21195530/does-turning-off-curlopt-ssl-verifypeer-in-curl-make-transmission-insecure
- https://stackoverflow.com/questions/4660610/if-curlopt-ssl-verifypeer-is-false-is-the-data-transfer-no-longer-secure
- https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/

### CODE REVIEW

**Comment by mehdikhody** [comment]
Hi, thanks for your suggestion.
I know requests will be more secure but sending them also be slow too.

`CURLOPT_SSL_VERIFYPEER` also require another option that name is `CURLOPT_CAINFO`.
this option holding one or more certificates to verify and it's need to be set by developers.

Every developers can set `CURLOPT_SSL_VERIFYPEER` by themself.

**Comment by moebrowne** [comment]
Can you quote a source for your assertion that verified requests are slower?

While it is true that `CURLOPT_CAINFO` has to be set correctly (or even better `curl.cainfo` in php.ini) disabling verification makes this codebase unsecure by default.

Perhaps a good middle ground would be to add a condition which checks if `curl.cainfo` has been set and if so enables peer verification rather than relying on developers to read through the code base to secure their apps?

**Comment by mehdikhody** [comment]
Now you can see these lines in `Request.php`:
```php
if (ini_get('curl.cainfo') !== '') $curl->setOptions([
    CURLOPT_SSL_VERIFYPEER => true
]); 
```

**Comment by moebrowne** [comment]
Looks good :+1: 

I would still be interested to hear if you had any information on peer verification being slower?

**Pull request closed without merging**
